[package]
name = "seven_wonders"
version = "0.1.0"
authors = ["Technici4n"]
edition = "2018"

[dependencies]
actix-web = "1.0"
actix = "0.8"
actix-web-actors = "1.0"
actix-files = "0.1"
actix-rt = "0.2"
serde = "1.0"
serde_json = "1.0"
